name: Build and push to app
on:
  push:
    branches:
      - master # [$default-branch]
  pull_request:
    branches:
      - master # [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.11
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm test --if-present

      - run: npm run build --if-present

      - name: Change assets paths
        run: |
          chmod +x ./.github/workflows/change-links.sh
          cd dist
          bash ./.github/workflows/change-links.sh '/assets' '/assets/manictime_integration'
          sed -n '14,15p;16q' index
          cd ..

      - name: Copy dest folder
        run: |
          mkdir -v ../dist
          find dist -type f -exec cp {} ../dist \;
          cd ..

      - name: Clone erpapp repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.erpapp_pat }}
          repository: K0ch3rga/erpnext-manictime-erpapp

      - name: Change erprepo files
        run: |
          rm -r manictime_integration/public/*
          cp -f ../dist/* manictime_integration/public/

      - name: Log project structure if failed
        if: failure()
        run: |
          echo '~~~~~~~~~~ root dir ~~~~~~~~~~'
          ls -la ..
          echo '~~~~~~~~~~ erp dir ~~~~~~~~~~'
          ls -la
          echo '~~~~~~~~~~ erp app dir ~~~~~~~~~~'
          ls -la manictime_integration
          echo '~~~~~~~~~~ dist dir ~~~~~~~~~~'
          ls -la manictime_integration/dist

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          sign-commits: true
          assignees: K0ch3rga
          token: ${{ secrets.erpapp_pat }}
