name: Build and push to app
on:
  push:
    branches:
      - master # [$default-branch]
  pull_request:
    branches:
      - master # [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.11
        uses: actions/setup-node@v4
        with:
          node-version: 22.11
          cache: 'npm'

      - run: npm ci

      - run: npm test --if-present

      - run: npm run build --if-present

      - name: Change assets paths
        run: |
          chmod +x ./.github/workflows/change-links.sh
          bash ./.github/workflows/change-links.sh '/assets' '/assets/manictime_integration'

      - run: |
          ls -la
          cd ..
          ls -la

      - name: Clone erpapp repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.erpapp_pat }}
          repository: K0ch3rga/erpnext-manictime-erpapp

      - run: |
          ls
          echo '~~~~~~~~~~~~~~~~~~'
          ls manictime_integration
          echo '~~~~~~~~~~~~~~~~~~'
          ls -la ..
          echo '~~~~~~~~~~~~~~~~~~'
          ls -la ../erp-manictime-front

      - name: Change erprepo files
        run: |
          rm -r manictime_integration/public/*
          cp -r ../erp-manictime-front/dist/* manictime_integration/public/*

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          sign-commits: true
          assignees: K0ch3rga
          reviewers: K0ch3rga
          token: ${{ secrets.erpapp_pat }}
